name: CodePush

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      platform:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    environment: client-${{ inputs.environment }}
    env:
      BUILD_DIR: ./build
      SOURCEMAPS_DIR: ./build/sourcemaps

      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ vars.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}

      APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
      ANDROID_CODE_PUSH_PROJECT: ${{ vars.ANDROID_CODE_PUSH_PROJECT }}
      IOS_CODE_PUSH_PROJECT: ${{ vars.IOS_CODE_PUSH_PROJECT }}

      DOTENV_ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      DOTENV_DEBUG: ${{ vars.DEBUG }}
      DOTENV_ANDROID_CODE_PUSH_DEPLOYMENT_KEY: ${{ vars.ANDROID_CODE_PUSH_DEPLOYMENT_KEY }}
      DOTENV_ANDROID_PACKAGE_NAME: ${{ vars.ANDROID_PACKAGE_NAME }}
      DOTENV_API_ENDPOINT: ${{ vars.API_ENDPOINT }}
      DOTENV_DEEP_LINK_PREFIX: ${{ vars.DEEP_LINK_PREFIX }}
      DOTENV_DEEP_LINK_SCHEME: ${{ vars.DEEP_LINK_SCHEME }}
      DOTENV_IOS_APPSTORE_ID: ${{ vars.IOS_APPSTORE_ID }}
      DOTENV_IOS_CODE_PUSH_DEPLOYMENT_KEY: ${{ vars.IOS_CODE_PUSH_DEPLOYMENT_KEY }}
      DOTENV_METRICS_ENDPOINT: ${{ vars.METRICS_ENDPOINT }}
      DOTENV_POSTHOG_API_KEY: ${{ vars.POSTHOG_API_KEY }}
      DOTENV_SENTRY_DSN: ${{ vars.SENTRY_DSN }}
      DOTENV_STORAGE_ENDPOINT: ${{ vars.STORAGE_ENDPOINT }}
      DOTENV_STRIPE_APPLE_MERCHANT_IDENTIFIER: ${{ vars.STRIPE_APPLE_MERCHANT_IDENTIFIER }}
      DOTENV_STRIPE_PUBLISHABLE_KEY: ${{ vars.STRIPE_PUBLISHABLE_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Create Dotenv File
        uses: iamsauravsharma/create-dotenv@v1.2.1
        with:
          env-prefix: DOTENV_
          directory: ./client

      - name: Cache Shared Dependencies
        id: cache-shared-node-modules
        uses: actions/cache@v2
        with:
          path: ./shared/node_modules
          key: shared-node-modules-${{ hashFiles('./shared/yarn.lock') }}

      - name: Install Shared Dependencies
        if: steps.cache-shared-node-modules.outputs.cache-hit != 'true'
        working-directory: ./shared
        run: yarn

      - name: Cache Content Dependencies
        id: cache-content-node-modules
        uses: actions/cache@v2
        with:
          path: ./content/node_modules
          key: content-node-modules-${{ hashFiles('./content/yarn.lock') }}

      - name: Install Content Dependencies
        if: steps.cache-content-node-modules.outputs.cache-hit != 'true'
        working-directory: ./content
        run: yarn

      - name: Cache Client Dependencies
        id: cache-client-node-modules
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: client-node-modules-${{ hashFiles('./client/yarn.lock') }}

      - name: Install Client Dependencies
        if: steps.cache-client-node-modules.outputs.cache-hit != 'true'
        working-directory: ./client
        run: yarn

      - name: Build Content
        working-directory: ./content
        run: yarn build

      - name: Prepare Build Directory
        working-directory: ./client
        run: mkdir -p $SOURCEMAPS_DIR

      - name: Prepare $GIT_COMMIT_SHORT
        working-directory: ./shared
        run: ./scripts/getGitCommitShort.sh >> $GITHUB_ENV

      - name: Codepush Android
        working-directory: ./client
        if: inputs.platform == 'android'
        run: >
          yarn appcenter codepush release-react
          --app $ANDROID_CODE_PUSH_PROJECT
          --deployment-name ${{ secrets.ENVIRONMENT }}
          --output-dir $BUILD_DIR
          --sourcemap-output-dir $SOURCEMAPS_DIR
          --disable-duplicate-release-error

      - name: Codepush iOS
        working-directory: ./client
        if: inputs.platform == 'ios'
        run: >
          yarn appcenter codepush release-react
          --app $IOS_CODE_PUSH_PROJECT
          --deployment-name ${{ secrets.ENVIRONMENT }}
          --plist-file ./ios/Supporting/Info.plist
          --xcode-project-file ./ios/twentyninek.xcodeproj
          --output-dir $BUILD_DIR
          --sourcemap-output-dir $SOURCEMAPS_DIR
          --disable-duplicate-release-error

      - name: Upload Android Source Maps to Sentry
        working-directory: ./client
        if: inputs.platform == 'android'
        run: >
          yarn sentry-cli react-native appcenter
          $ANDROID_CODE_PUSH_PROJECT android
          $BUILD_DIR/CodePush $SOURCEMAPS_DIR
          --deployment ${{ secrets.ENVIRONMENT }}
          --dist ${{ secrets.ENVIRONMENT }}
          --release-name $GIT_COMMIT_SHORT

      - name: Upload iOS Source Maps to Sentry
        working-directory: ./client
        if: inputs.platform == 'ios'
        run: >
          yarn sentry-cli react-native appcenter
          $IOS_CODE_PUSH_PROJECT ios
          $BUILD_DIR/CodePush $SOURCEMAPS_DIR
          --deployment ${{ secrets.ENVIRONMENT }}
          --dist ${{ secrets.ENVIRONMENT }}
          --release-name $GIT_COMMIT_SHORT

      - name: Associate Commits to Sentry Release
        working-directory: ./client
        run: yarn sentry-cli releases set-commits --auto $GIT_COMMIT_SHORT
