name: Web

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: web-${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache Root Dependencies
        id: cache-root-node-modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: node-modules-${{ hashFiles('./yarn.lock') }}

      - name: Install Root Dependencies
        if: steps.cache-root-node-modules.outputs.cache-hit != 'true'
        run: yarn --network-concurrency 1

      - name: Cache Shared Dependencies
        id: cache-shared-node-modules
        uses: actions/cache@v4
        with:
          path: ./shared/node_modules
          key: shared-node-modules-${{ hashFiles('./shared/yarn.lock') }}

      - name: Install Shared Dependencies
        if: steps.cache-shared-node-modules.outputs.cache-hit != 'true'
        working-directory: ./shared
        run: yarn --network-concurrency 1

      - name: Cache Content Dependencies
        id: cache-content-node-modules
        uses: actions/cache@v4
        with:
          path: ./content/node_modules
          key: content-node-modules-${{ hashFiles('./content/yarn.lock') }}

      - name: Install Content Dependencies
        if: steps.cache-content-node-modules.outputs.cache-hit != 'true'
        working-directory: ./content
        run: yarn --network-concurrency 1

      - name: Cache Client Dependencies
        id: cache-client-node-modules
        uses: actions/cache@v4
        with:
          path: ./client/node_modules
          key: client-node-modules-${{ hashFiles('./client/yarn.lock') }}

      - name: Install Client Dependencies
        if: steps.cache-client-node-modules.outputs.cache-hit != 'true'
        working-directory: ./client
        run: yarn --network-concurrency 1

      - name: Cache web Dependencies
        id: cache-web-node-modules
        uses: actions/cache@v4
        with:
          path: ./web/node_modules
          key: web-node-modules-${{ hashFiles('./web/yarn.lock') }}

      - name: Install Web Dependencies
        if: steps.cache-web-node-modules.outputs.cache-hit != 'true'
        working-directory: ./web
        run: yarn --network-concurrency 1

      - name: Build Content
        working-directory: ./content
        run: yarn build

      - name: Build Web
        working-directory: ./web
        run: yarn build

      - name: Deploy Web
        run: >
          yarn firebase deploy
          --project ${{ secrets.FIREBASE_PROJECT }}
          --token ${{ secrets.FIREBASE_TOKEN }}
          --only hosting:cupcake-web
          --non-interactive
